In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\User\Documents\SQL\Credit Risk Analysis Project\Raw Data\german_credit_data.csv")
df

,status_account,month_duration,credit_history,purpose,credit_amount,status_savings,years_employment,payment_to_income_ratio,status_and_sex,secondary_obligor,...,collateral,age,other_installment_plans,housing,n_credits,job,n_guarantors,telephone,is_foreign_worker,target
0,< 0 DM,6,critical account/ other credits existing (not ...,radio/television,1169,unknown/ no savings account,>= 7 years,4,male : single,none,...,none,67,none,own,2,skilled employee/ official,1,"yes, registered under the customers name",yes,good
1,0 to < 200 DM,48,existing credits paid back duly till now,radio/television,5951,< 100 DM,1 to < 4 years,2,female : divorced/separated/married,none,...,none,22,none,own,1,skilled employee/ official,1,none,yes,bad
2,no checking account,12,critical account/ other credits existing (not ...,education,2096,< 100 DM,4 to < 7 years,2,male : single,none,...,none,49,none,own,1,unskilled - resident,2,none,yes,good
3,< 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,< 100 DM,4 to < 7 years,2,male : single,guarantor,...,car,45,none,for free,1,skilled employee/ official,2,none,yes,good
4,< 0 DM,24,delay in paying off in the past,car (new),4870,< 100 DM,1 to < 4 years,3,male : single,none,...,savings agreement/life insurance,53,none,for free,2,skilled employee/ official,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,no checking account,12,existing credits paid back duly till now,furniture/equipment,1736,< 100 DM,4 to < 7 years,3,female : divorced/separated/married,none,...,none,31,none,own,1,unskilled - resident,1,none,yes,good
996,< 0 DM,30,existing credits paid back duly till now,car (used),3857,< 100 DM,1 to < 4 years,4,male : divorced/separated,none,...,car,40,none,own,1,management/ self-employed/highly qualified emp...,1,"yes, registered under the customers name",yes,good
997,no checking account,12,existing credits paid back duly till now,radio/television,804,< 100 DM,>= 7 years,4,male : single,none,...,real estate,38,none,own,1,skilled employee/ official,1,none,yes,good
998,< 0 DM,45,existing credits paid back duly till now,radio/television,1845,< 100 DM,1 to < 4 years,4,male : single,none,...,savings agreement/life insurance,23,none,for free,1,skilled employee/ official,1,"yes, registered under the customers name",yes,bad
999,0 to < 200 DM,45,critical account/ other credits existing (not ...,car (used),4576,100 to < 500 DM,unemployed,3,male : single,none,...,real estate,27,none,own,1,skilled employee/ official,1,none,yes,good

In [5]:
df.head()

,status_account,month_duration,credit_history,purpose,credit_amount,status_savings,years_employment,payment_to_income_ratio,status_and_sex,secondary_obligor,...,collateral,age,other_installment_plans,housing,n_credits,job,n_guarantors,telephone,is_foreign_worker,target
0,< 0 DM,6,critical account/ other credits existing (not ...,radio/television,1169,unknown/ no savings account,>= 7 years,4,male : single,none,...,none,67,none,own,2,skilled employee/ official,1,"yes, registered under the customers name",yes,good
1,0 to < 200 DM,48,existing credits paid back duly till now,radio/television,5951,< 100 DM,1 to < 4 years,2,female : divorced/separated/married,none,...,none,22,none,own,1,skilled employee/ official,1,none,yes,bad
2,no checking account,12,critical account/ other credits existing (not ...,education,2096,< 100 DM,4 to < 7 years,2,male : single,none,...,none,49,none,own,1,unskilled - resident,2,none,yes,good
3,< 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,< 100 DM,4 to < 7 years,2,male : single,guarantor,...,car,45,none,for free,1,skilled employee/ official,2,none,yes,good
4,< 0 DM,24,delay in paying off in the past,car (new),4870,< 100 DM,1 to < 4 years,3,male : single,none,...,savings agreement/life insurance,53,none,for free,2,skilled employee/ official,2,none,yes,bad

In [6]:
df.shape

(1000, 21)

In [7]:
df.columns

Index(['status_account', 'month_duration', 'credit_history', 'purpose',
       'credit_amount', 'status_savings', 'years_employment',
       'payment_to_income_ratio', 'status_and_sex', 'secondary_obligor',
       'residence_since', 'collateral', 'age', 'other_installment_plans',
       'housing', 'n_credits', 'job', 'n_guarantors', 'telephone',
       'is_foreign_worker', 'target'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   status_account           1000 non-null   object
 1   month_duration           1000 non-null   int64
 2   credit_history           1000 non-null   object
 3   purpose                  1000 non-null   object
 4   credit_amount            1000 non-null   int64
 5   status_savings           1000 non-null   object
 6   years_employment         1000 non-null   object
 7   payment_to_income_ratio  1000 non-null   int64
 8   status_and_sex           1000 non-null   object
 9   secondary_obligor        1000 non-null   object
 10  residence_since          1000 non-null   int64
 11  collateral               1000 non-null   object
 12  age                      1000 non-null   int64
 13  other_installment_plans  1000 non-null   object
 14  housing                  1000 non-null   object
 15  n_credits                1000 non-null   int64
 16  job                      1000 non-null   object
 17  n_guarantors             1000 non-null   int64
 18  telephone                1000 non-null   object
 19  is_foreign_worker        1000 non-null   object
 20  target                   1000 non-null   object
dtypes: int64(7), object(14)
memory usage: 164.2+ KB

In [9]:
df.isnull().sum()

status_account             0
month_duration             0
credit_history             0
purpose                    0
credit_amount              0
status_savings             0
years_employment           0
payment_to_income_ratio    0
status_and_sex             0
secondary_obligor          0
residence_since            0
collateral                 0
age                        0
other_installment_plans    0
housing                    0
n_credits                  0
job                        0
n_guarantors               0
telephone                  0
is_foreign_worker          0
target                     0
dtype: int64

In [10]:
df['target'].value_counts()

target
good    700
bad     300
Name: count, dtype: int64

In [11]:
df['target'].value_counts(normalize=True) * 100

target
good    70.0
bad     30.0
Name: proportion, dtype: float64

In [12]:
df.describe()

,month_duration,credit_amount,payment_to_income_ratio,residence_since,age,n_credits,n_guarantors
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [13]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

status_account
status_account
no checking account    394
< 0 DM                 274
0 to < 200 DM          269
>= 200 DM               63
Name: count, dtype: int64

credit_history
credit_history
existing credits paid back duly till now                       530
critical account/ other credits existing (not at this bank)    293
delay in paying off in the past                                 88
all credits at this bank paid back duly                         49
no credits taken/ all credits paid back duly                    40
Name: count, dtype: int64

purpose
purpose
radio/television       280
car (new)              234
furniture/equipment    181
car (used)             103
business                97
education               50
repairs                 22
domestic appliances     12
others                  12
retraining               9
Name: count, dtype: int64

status_savings
status_savings
< 100 DM                       603
unknown/ no savings account    183
100 to < 500 DM                103
500 to < 1000 DM                63
>= 1000 DM                      48
Name: count, dtype: int64

years_employment
years_employment
1 to < 4 years    339
>= 7 years        253
4 to < 7 years    174
< 1 year          172
unemployed         62
Name: count, dtype: int64

status_and_sex
status_and_sex
male : single                          548
female : divorced/separated/married    310
male : married/widowed                  92
male : divorced/separated               50
Name: count, dtype: int64

secondary_obligor
secondary_obligor
none            907
guarantor        52
co-applicant     41
Name: count, dtype: int64

collateral
collateral
real estate                         332
none                                282
car                                 232
savings agreement/life insurance    154
Name: count, dtype: int64

other_installment_plans
other_installment_plans
none      814
bank      139
stores     47
Name: count, dtype: int64

housing
housing
own         713
rent        179
for free    108
Name: count, dtype: int64

job
job
skilled employee/ official                             630
unskilled - resident                                   200
management/ self-employed/highly qualified employee    148
unemployed/ unskilled - non-resident                    22
Name: count, dtype: int64

telephone
telephone
none                                        596
yes, registered under the customers name    404
Name: count, dtype: int64

is_foreign_worker
is_foreign_worker
yes    963
no      37
Name: count, dtype: int64

target
target
good    700
bad     300
Name: count, dtype: int64

In [14]:
df.columns = df.columns.str.lower()

In [15]:
df.rename(columns={
    'month_duration': 'loan_duration_months',
    'credit_amount': 'loan_amount',
    'n_credits': 'number_of_credits'
}, inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df['target_binary'] = df['target'].map({
    'good': 0,
    'bad': 1
})

In [18]:
## feature engineering

In [19]:
## Feature 1 — Age Group

df['age_group'] = pd.cut(
    df['age'],
    bins=[18,25,35,50,100],
    labels=['18-25','26-35','36-50','50+']
)

In [20]:
## Feature 2 — Loan Size Category

df['loan_size'] = pd.qcut(
    df['loan_amount'],
    q=3,
    labels=['Small','Medium','Large']
)

In [21]:
## Feature 3 — Risky Employment Flag

df['employment_risk'] = np.where(
    df['years_employment'].isin([
        'unemployed',
        '< 1 year'
    ]),
    'High Risk',
    'Stable'
)

In [22]:
## Feature 4 — High Loan Flag

df['high_loan_flag'] = np.where(
    df['loan_amount'] > df['loan_amount'].median(),
    1,
    0
)

In [23]:
df

,status_account,loan_duration_months,credit_history,purpose,loan_amount,status_savings,years_employment,payment_to_income_ratio,status_and_sex,secondary_obligor,...,job,n_guarantors,telephone,is_foreign_worker,target,target_binary,age_group,loan_size,employment_risk,high_loan_flag
0,< 0 DM,6,critical account/ other credits existing (not ...,radio/television,1169,unknown/ no savings account,>= 7 years,4,male : single,none,...,skilled employee/ official,1,"yes, registered under the customers name",yes,good,0,50+,Small,Stable,0
1,0 to < 200 DM,48,existing credits paid back duly till now,radio/television,5951,< 100 DM,1 to < 4 years,2,female : divorced/separated/married,none,...,skilled employee/ official,1,none,yes,bad,1,18-25,Large,Stable,1
2,no checking account,12,critical account/ other credits existing (not ...,education,2096,< 100 DM,4 to < 7 years,2,male : single,none,...,unskilled - resident,2,none,yes,good,0,36-50,Medium,Stable,0
3,< 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,< 100 DM,4 to < 7 years,2,male : single,guarantor,...,skilled employee/ official,2,none,yes,good,0,36-50,Large,Stable,1
4,< 0 DM,24,delay in paying off in the past,car (new),4870,< 100 DM,1 to < 4 years,3,male : single,none,...,skilled employee/ official,2,none,yes,bad,1,50+,Large,Stable,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,no checking account,12,existing credits paid back duly till now,furniture/equipment,1736,< 100 DM,4 to < 7 years,3,female : divorced/separated/married,none,...,unskilled - resident,1,none,yes,good,0,26-35,Medium,Stable,0
996,< 0 DM,30,existing credits paid back duly till now,car (used),3857,< 100 DM,1 to < 4 years,4,male : divorced/separated,none,...,management/ self-employed/highly qualified emp...,1,"yes, registered under the customers name",yes,good,0,36-50,Large,Stable,1
997,no checking account,12,existing credits paid back duly till now,radio/television,804,< 100 DM,>= 7 years,4,male : single,none,...,skilled employee/ official,1,none,yes,good,0,36-50,Small,Stable,0
998,< 0 DM,45,existing credits paid back duly till now,radio/television,1845,< 100 DM,1 to < 4 years,4,male : single,none,...,skilled employee/ official,1,"yes, registered under the customers name",yes,bad,1,18-25,Medium,Stable,0
999,0 to < 200 DM,45,critical account/ other credits existing (not ...,car (used),4576,100 to < 500 DM,unemployed,3,male : single,none,...,skilled employee/ official,1,none,yes,good,0,26-35,Large,High Risk,1

In [25]:
df.to_csv("cleaned_credit_data.csv", index=False)